name: Tables
main: com.webkonsept.bukkit.tables.Tables
version: 0.6
branch: stable
thread: http://forums.bukkit.org/threads/Tables.20923/
website: http://minecraft.webkonsept.com/plugins/details/Tables.html
location: http://minecraft.webkonsept.com/plugins/download/Tables.jar
database: false
categories: [MECH]
description: Allows pressure plates on top of more blocks.
maintainer: DemmyDemon
authors: [DemmyDemon]
