name: Tables
main: com.webkonsept.bukkit.tables.Tables
version: 0.1
website: http://minecraft.webkonsept.com/
author: Fredrik Vold
database: false
description: >
        Allows pressure plates to be placed on top of including fence posts and glass.
commands:
