name: Tables
main: com.webkonsept.bukkit.tables.Tables
version: 0.4
website: http://minecraft.webkonsept.com/plugins/details/Tables.jar
location: http://minecraft.webkonsept.com/plugins/download/Tables.jar
author: Fredrik Vold
database: false
description: Allows pressure plates to be placed on top of fence posts and glass.
commands:
bukget: true
thread: http://forums.bukkit.org/threads/Tables.20923/
build:
    min: 935
    max: 953
categories:
    - MECH
